name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    strategy:
      fail-fast: true
      matrix:
        python-version: ['3.12']
        os: [ubuntu-latest]

    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Project Dependencies
        run: |
          pip install '.[test]'

      - name: Look for style errors
        run: flake8 app core tests --ignore=E501

      - name: Checking for importing style
        run: isort --profile=black --check --diff app core tests

      - name: Look for auto format errors
        run: black --check --diff app core tests


  test:
    runs-on: ubuntu-latest

    needs: lint

    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.12']

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Install Project
        run: |
          pip install '.[test]'
      - name: Run tests
        run: python manage.py test
